"""Pipeline runner — executes a pipeline's passes in order over a source document.

Runs each pass, evaluates its deterministic gates, and STOPS on a critical gate
failure (marking the run failed). The output is always a governed VAS *draft*
(source ``vainasherstudios_pipeline``, owned/draft, customer_safe=False, human review
required) — never auto-published, never canonical. Persistence and UI come later; this
returns an in-memory PipelineResult the caller stores.
"""
from __future__ import annotations
import dataclasses
from typing import Callable, List, Optional

from refinery.core import (
    Classification, SourceDoc, deterministic_classify, suggest_canonical_target,
)
from refinery.pipeline.passes import PassDeps, run_pass
from refinery.pipeline.schema import PipelineConfig
from refinery.pipeline.state import PipelineState
from refinery.pipeline.validators import evaluate_gates


@dataclasses.dataclass
class PipelineResult:
    status: str                        # completed | failed
    state: PipelineState
    draft: SourceDoc
    classification: Classification
    gate_failures: List[dict] = dataclasses.field(default_factory=list)

    def to_dict(self) -> dict:
        return {'status': self.status, 'state': self.state.to_dict(),
                'draft_title': self.draft.title, 'gate_failures': self.gate_failures}


def _build_draft(state: PipelineState, deps: PassDeps) -> tuple:
    """Build the governed VAS draft document + classification from the final state."""
    md = state.current_markdown or ''
    title = next((l[2:].strip() for l in md.splitlines() if l.startswith('# ')),
                 f'VainAsherStudios {(state.target_action or "document").replace("rewrite_into_", "").replace("_", " ").title()}')
    draft = SourceDoc(title=title, content=md, source='vainasherstudios_pipeline', source_id='',
                      raw_metadata={'pipeline_generated': True, 'human_review_required': True,
                                    'seo_metadata': state.seo_metadata, 'source_doc_ids': state.source_doc_ids})
    c = deterministic_classify(draft, deps.taxonomy or {})
    # Deterministic governance for pipeline output — owned VAS draft, never canonical/safe.
    c.source_org = 'vainasherstudios'; c.source_role = 'owned'; c.reuse_policy = 'owned_original'
    c.authority = 'draft'; c.rewrite_status = 'draft_generated'; c.review_status = 'needs_review'
    c.adaptation_action = state.target_action or c.adaptation_action
    c.customer_safe = False; c.canonical = False
    if state.service not in ('', 'unknown'):
        c.service = state.service
    if state.audience not in ('', 'unknown'):
        c.audience = state.audience
    c.transform_notes = f'Generated by enrichment pipeline ({len(state.pass_reports)} passes). Human review required.'
    c.tags = sorted(set(c.tags + ['pipeline-generated', 'draft-generated', 'human-review-required']))
    c.canonical_target = suggest_canonical_target(c)
    return draft, c


def run_pipeline(config: PipelineConfig, deps: PassDeps, *,
                 target_action: str = 'rewrite_into_customer_guide',
                 service: str = 'unknown', audience: str = 'unknown',
                 source_doc_ids: Optional[List[int]] = None,
                 progress: Optional[Callable[[int, int, str], None]] = None) -> PipelineResult:
    state = PipelineState(source_doc_ids=source_doc_ids or [], target_action=target_action,
                          service=service, audience=audience)
    # Seed the working markdown with the source; the clean pass tidies it, the draft
    # pass replaces it with an original VAS draft built from approved facts.
    state.current_markdown = deps.source_content or (deps.source_doc.content if deps.source_doc else '')

    status = 'completed'
    gate_failures: List[dict] = []
    for pc in config.passes:
        report = run_pass(pc, state, deps)
        gres = evaluate_gates(pc.gates, state, deps)
        report.metadata['gate_results'] = gres
        state.pass_reports[-1] = report.to_dict()        # re-snapshot with gate results
        if progress:
            progress(len(state.pass_reports), len(config.passes), pc.id)
        crit = [g for g in gres if g.get('critical') and not g.get('passed')]
        if report.status == 'gate_failed' or crit:
            status = 'failed'
            gate_failures.extend(crit or [{'name': pc.id, 'message': 'pass reported gate_failed', 'critical': True}])
            break                                        # stop on critical failure

    draft, classification = _build_draft(state, deps)
    return PipelineResult(status=status, state=state, draft=draft, classification=classification,
                          gate_failures=gate_failures)
